# =================================================================
# Unified Olist Project Profiles Configuration
# =================================================================
# 
# This profiles.yml file supports the complete Olist data pipeline:
# 
# 1. MELTANO PROJECT (meltano_olist):
#    - Extract data from Supabase PostgreSQL
#    - Load raw data into BigQuery olist_raw dataset
# 
# 2. DBT PROJECT (dbt_olist) - 3-Layer Architecture:
#    - PART 1: Staging - Clean raw data → olist_stag dataset
#    - PART 2: Warehouse - Build star schema → olist_warehouse dataset  
#    - PART 3: Analytics - Create mart views → olist_analytics dataset
#
# Author: M2Project Team
# Last Updated: August 31, 2025
# =================================================================

# 1. MELTANO PROJECT: Extract from Supabase → Load to BigQuery olist_raw
meltano_olist:
  target: staging
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: extended-legend-470014-n7
      dataset: olist_raw
      location: US
      keyfile: /Users/jefflee/SCTP/M2Project/extended-legend-470014-n7-db75dec7d87a.json
      job_execution_timeout_seconds: 300
      maximum_bytes_billed: 1000000000
      priority: interactive
      job_retries: 1

    # PART 1: Staging - Clean olist_raw → olist_staging
    staging:
      type: bigquery
      method: service-account
      project: extended-legend-470014-n7
      dataset: olist_staging
      location: US
      keyfile: /Users/jefflee/SCTP/M2Project/extended-legend-470014-n7-db75dec7d87a.json
      job_execution_timeout_seconds: 300
      maximum_bytes_billed: 1000000000
      priority: interactive
      job_retries: 1

    # PART 2: Warehouse - Star schema with 1 fact + 8 dim tables
    warehouse:
      type: bigquery
      method: service-account
      project: extended-legend-470014-n7
      dataset: olist_warehouse
      location: US
      keyfile: /Users/jefflee/SCTP/M2Project/extended-legend-470014-n7-db75dec7d87a.json
      job_execution_timeout_seconds: 300
      maximum_bytes_billed: 1000000000
      priority: interactive
      job_retries: 1

    # PART 3: Analytics - Mart views for business objectives
    analytics:
      type: bigquery
      method: service-account
      project: extended-legend-470014-n7
      dataset: olist_analytics
      location: US
      keyfile: /Users/jefflee/SCTP/M2Project/extended-legend-470014-n7-db75dec7d87a.json
      job_execution_timeout_seconds: 300
      maximum_bytes_billed: 1000000000
      priority: interactive
      job_retries: 1
