name: 'dbt_olist'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'meltano_olist'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configure materializations for 3-layer architecture
models:
  dbt_olist:
    # Part 1: Staging - Clean raw data → olist_stag
    staging:
      +materialized: table
    # Part 2: Warehouse - Star schema → olist_warehouse  
    warehouse:
      +materialized: table
    # Part 3: Analytics - Mart views → olist_analytics
    marts:
      +materialized: view

# # Configuring tests
# tests:
#   +store_failures: true
#   +schema: "dbt_test_audit"

# vars:
#   # The `start_date` variable will be accessible in all resources
#   start_date: '2016-01-01'
#   # This is the end date for data processing
#   end_date: '2018-12-31'
