name: 'dbt_olist'
version: '1.0.0'
config-version: 2

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_olist'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"
clean-targets:         # directories to be removed by `dbt clean`
  - "target"
  - "dbt_packages"

# Configure materializations
models:
  dbt_olist:
    # Config indicated by + and applies to all files under models/staging/
    staging:
      +materialized: view
    # Config for models under intermediate/
    intermediate:
      +materialized: ephemeral
    # Config for models under marts/
    marts:
      +materialized: table

# Configuring tests
tests:
  +store_failures: true
  +schema: "dbt_test_audit"

vars:
  # The `start_date` variable will be accessible in all resources
  start_date: '2016-01-01'
  # This is the end date for data processing
  end_date: '2018-12-31'
