dbt_transform_olist:
  target: dev
  outputs:
    dev:
      type: bigquery
      method: service-account
      project: extended-legend-470014-n7
      dataset: olist_staging
      location: US
      keyfile: /Users/jefflee/SCTP/M2Project/extended-legend-470014-n7-db75dec7d87a.json
      job_execution_timeout_seconds: 300
      maximum_bytes_billed: 1000000000
      priority: interactive
      job_retries: 1
      
    # staging:
    #   type: bigquery
    #   method: service-account
    #   project: extended-legend-470014-n7
    #   dataset: olist_staging
    #   location: US
    #   keyfile: /Users/jefflee/SCTP/M2Project/extended-legend-470014-n7-db75dec7d87a.json
    #   timeout_seconds: 300
    #   maximum_bytes_billed: 1000000000
    #   priority: interactive
    #   retries: 1
      
    # prod:
    #   type: bigquery
    #   method: service-account
    #   project: extended-legend-470014-n7
    #   dataset: olist_analytics
    #   location: US
    #   keyfile: /Users/jefflee/SCTP/M2Project/extended-legend-470014-n7-db75dec7d87a.json
    #   timeout_seconds: 300
    #   maximum_bytes_billed: 1000000000
    #   priority: interactive
    #   retries: 1