# Clean Olist dbt Project Configuration
# ========================================
#
# This dbt project works with data loaded by Meltano into BigQuery
# Source dataset: olist_raw (loaded by Meltano)
# Target datasets: olist_staging, olist_analytics
#
# Author: M2Project Team
# Last Updated: August 31, 2025
# ========================================

name: 'dbt_clean_olist'
version: '1.0.0'

# This setting configures which "profile" dbt uses for this project.
profile: 'dbt_clean_olist'

# These configurations specify where dbt should look for different types of files.
model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

clean-targets:
  - "target"
  - "dbt_packages"

# Configuring models
models:
  dbt_clean_olist:
    # Staging models - clean and standardize raw data
    staging:
      +materialized: view
      +schema: staging

    # Intermediate models - business logic and transformations
    intermediate:
      +materialized: view
      +schema: intermediate

    # Mart models - final dimensional models for analytics
    marts:
      +materialized: table
      +schema: marts
